services:
  web:
    image: nginx:latest
    environment:
      - API_URL=http://backend:8080/
      - FRONTEND_URL=https://comic-generator-app.vercel.app/
    volumes:
      - ./nginx.template:/etc/nginx/templates/nginx.conf.template
    command: /bin/bash -c "envsubst '\$API_URL \$FRONTEND_URL' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
