services:
  web:
    image: nginx:latest
    environment:
      - API_URL=http://backend:8080/
      - FRONTEND_URL=https://comic-generator-app.vercel.app/
    volumes:
      - ./nginx.template:/etc/nginx/nginx.template
      - /etc/nginx/ssl:/etc/nginx/ssl
    command: /bin/bash -c "cat /etc/nginx/nginx.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
