services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_NAME=comicdb
      - DB_USER=comicuser
      - DB_PASSWORD=comicpass
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: comicuser
      POSTGRES_PASSWORD: comicpass
      POSTGRES_DB: comicdb
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
