services:
  web:
    image: nginx:latest
    environment:
      - API_URL=http://backend:8080/
      - FRONTEND_URL=https://comic-generator-app.vercel.app/
    volumes:
      - ./nginx.template:/etc/nginx/nginx.conf
      - /etc/nginx/ssl:/etc/nginx/ssl
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_HOST: db # Critical: this must be 'db', not localhost
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
